on:
  push:
    branches: [ feature/ci ]

env:
  AZURE_WEBAPP_NAME: josh.house    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './build'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.15.1'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install
      run: |
        npm install
    - name: Build
      run: |
        npm run-script build --if-present
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1
      with:
        source-path: build
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}
