name: "Deployment"

on:
  push:
    branches: [ feature/ci ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install
      run: |
        npm install
    - name: Build
      run: |
        npm run-script build --if-present
    - name: Zip Build
      uses: montudor/action-zip@v0.1.1
      with:
        args: zip -qq -r build.zip build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build.zip
    - name: deploy
      uses: ambientlight/amplify-cli-action@0.2.1
      with:
        amplify_command: publish
        amplify_env: production
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-southeast-2
